apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application
spec:
  destination:
    namespace: user23-application
    server: "https://kubernetes.default.svc"
  project: default
  sources:
    - path: Argocd-instances/application
      repoURL: "https://github.com/tal-hason/dotnet-workshop-setup.git"
      targetRevision: main
      helm:
        valueFiles:
          - $values/GitOps/values.yaml
    - repoURL: "https://github.com/agindes/dotnet-app.git"
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
